// Code generated by protoc-gen-go. DO NOT EDIT.
// source: k8s_sim.proto

package simRPC

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 测试
// 返回四个关键值的str
type Metrics struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Nodes                *Nodes   `protobuf:"bytes,2,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Pods                 *Pods    `protobuf:"bytes,3,opt,name=pods,proto3" json:"pods,omitempty"`
	Queue                *Queue   `protobuf:"bytes,4,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c18405e8fba6db3, []int{0}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

func (m *Metrics) GetNodes() *Nodes {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Metrics) GetPods() *Pods {
	if m != nil {
		return m.Pods
	}
	return nil
}

func (m *Metrics) GetQueue() *Queue {
	if m != nil {
		return m.Queue
	}
	return nil
}

type Clock struct {
	Clock_Key            string   `protobuf:"bytes,1,opt,name=clock_Key,json=clockKey,proto3" json:"clock_Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clock) Reset()         { *m = Clock{} }
func (m *Clock) String() string { return proto.CompactTextString(m) }
func (*Clock) ProtoMessage()    {}
func (*Clock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c18405e8fba6db3, []int{1}
}

func (m *Clock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clock.Unmarshal(m, b)
}
func (m *Clock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clock.Marshal(b, m, deterministic)
}
func (m *Clock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clock.Merge(m, src)
}
func (m *Clock) XXX_Size() int {
	return xxx_messageInfo_Clock.Size(m)
}
func (m *Clock) XXX_DiscardUnknown() {
	xxx_messageInfo_Clock.DiscardUnknown(m)
}

var xxx_messageInfo_Clock proto.InternalMessageInfo

func (m *Clock) GetClock_Key() string {
	if m != nil {
		return m.Clock_Key
	}
	return ""
}

type Nodes struct {
	NodesMetricsKey      string   `protobuf:"bytes,1,opt,name=nodes_metrics_key,json=nodesMetricsKey,proto3" json:"nodes_metrics_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c18405e8fba6db3, []int{2}
}

func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (m *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(m, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodesMetricsKey() string {
	if m != nil {
		return m.NodesMetricsKey
	}
	return ""
}

type Pods struct {
	PodsMetricsKey       string   `protobuf:"bytes,1,opt,name=pods_metrics_key,json=podsMetricsKey,proto3" json:"pods_metrics_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pods) Reset()         { *m = Pods{} }
func (m *Pods) String() string { return proto.CompactTextString(m) }
func (*Pods) ProtoMessage()    {}
func (*Pods) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c18405e8fba6db3, []int{3}
}

func (m *Pods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pods.Unmarshal(m, b)
}
func (m *Pods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pods.Marshal(b, m, deterministic)
}
func (m *Pods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pods.Merge(m, src)
}
func (m *Pods) XXX_Size() int {
	return xxx_messageInfo_Pods.Size(m)
}
func (m *Pods) XXX_DiscardUnknown() {
	xxx_messageInfo_Pods.DiscardUnknown(m)
}

var xxx_messageInfo_Pods proto.InternalMessageInfo

func (m *Pods) GetPodsMetricsKey() string {
	if m != nil {
		return m.PodsMetricsKey
	}
	return ""
}

type Queue struct {
	QueueMetricsKey      string   `protobuf:"bytes,1,opt,name=queue_metrics_key,json=queueMetricsKey,proto3" json:"queue_metrics_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Queue) Reset()         { *m = Queue{} }
func (m *Queue) String() string { return proto.CompactTextString(m) }
func (*Queue) ProtoMessage()    {}
func (*Queue) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c18405e8fba6db3, []int{4}
}

func (m *Queue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Queue.Unmarshal(m, b)
}
func (m *Queue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Queue.Marshal(b, m, deterministic)
}
func (m *Queue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Queue.Merge(m, src)
}
func (m *Queue) XXX_Size() int {
	return xxx_messageInfo_Queue.Size(m)
}
func (m *Queue) XXX_DiscardUnknown() {
	xxx_messageInfo_Queue.DiscardUnknown(m)
}

var xxx_messageInfo_Queue proto.InternalMessageInfo

func (m *Queue) GetQueueMetricsKey() string {
	if m != nil {
		return m.QueueMetricsKey
	}
	return ""
}

type Result struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c18405e8fba6db3, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Metrics)(nil), "simRPC.Metrics")
	proto.RegisterType((*Clock)(nil), "simRPC.Clock")
	proto.RegisterType((*Nodes)(nil), "simRPC.Nodes")
	proto.RegisterType((*Pods)(nil), "simRPC.Pods")
	proto.RegisterType((*Queue)(nil), "simRPC.Queue")
	proto.RegisterType((*Result)(nil), "simRPC.Result")
}

func init() { proto.RegisterFile("k8s_sim.proto", fileDescriptor_4c18405e8fba6db3) }

var fileDescriptor_4c18405e8fba6db3 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x16, 0x65, 0xd1, 0x8e, 0xd2, 0xea, 0x1e, 0x0c, 0xd1, 0x0b, 0x41, 0x0f, 0x8d, 0x07, 0x62,
	0xe0, 0xe2, 0xc1, 0x5b, 0x8f, 0x8d, 0xa6, 0xce, 0x0b, 0x90, 0x08, 0x7b, 0x20, 0x14, 0xb7, 0xb2,
	0x70, 0xe8, 0xab, 0xf8, 0xb4, 0x66, 0x66, 0xd9, 0xa6, 0x4d, 0xb8, 0xc1, 0xf7, 0x33, 0xdf, 0x37,
	0x3b, 0x10, 0x36, 0x6f, 0xa6, 0x30, 0x75, 0x9b, 0xee, 0x3a, 0xdd, 0x6b, 0x19, 0x98, 0xba, 0xc5,
	0xcd, 0x2a, 0xf9, 0xf3, 0xe0, 0xf2, 0x43, 0xf5, 0x5d, 0x5d, 0x1a, 0xf9, 0x04, 0xa2, 0xdc, 0xea,
	0xb2, 0x89, 0xbc, 0xd8, 0x5b, 0x5e, 0x67, 0x61, 0x6a, 0x35, 0xe9, 0x8a, 0x40, 0xb4, 0x1c, 0x89,
	0x7e, 0x74, 0xa5, 0x4c, 0x74, 0x7e, 0x2a, 0xfa, 0x24, 0x10, 0x2d, 0x27, 0x63, 0xf0, 0x77, 0xba,
	0x32, 0xd1, 0x05, 0x6b, 0x6e, 0x9c, 0x66, 0xa3, 0x2b, 0x83, 0xcc, 0xd0, 0x98, 0xdf, 0x41, 0x0d,
	0x2a, 0xf2, 0x4f, 0xc7, 0x7c, 0x11, 0x88, 0x96, 0x4b, 0x9e, 0x41, 0x70, 0xb6, 0x7c, 0x84, 0x19,
	0xa7, 0x17, 0x6b, 0xb5, 0xe7, 0x76, 0x33, 0xbc, 0x62, 0x60, 0xad, 0xf6, 0x49, 0x0e, 0x82, 0xc3,
	0xe5, 0x0b, 0xdc, 0x71, 0x7c, 0xd1, 0xda, 0x85, 0x8a, 0xe6, 0xa0, 0x5e, 0x30, 0x31, 0x2e, 0x4a,
	0xa6, 0x57, 0xf0, 0xa9, 0x8d, 0x5c, 0xc2, 0x2d, 0xf5, 0x99, 0xb0, 0xcc, 0x09, 0x3f, 0x72, 0xe4,
	0x20, 0xb8, 0x1c, 0xc5, 0x70, 0xbd, 0xa9, 0x18, 0x26, 0x8e, 0x4c, 0x31, 0x04, 0xa8, 0xcc, 0xb0,
	0xed, 0xe5, 0x3d, 0x04, 0x1d, 0x7f, 0xb1, 0x54, 0xe0, 0xf8, 0x97, 0xbd, 0xc3, 0x78, 0x0a, 0x99,
	0x41, 0x88, 0xaa, 0xd4, 0x5d, 0xe5, 0xee, 0xb1, 0x70, 0x8f, 0x32, 0x02, 0x0f, 0x73, 0x07, 0xd8,
	0x99, 0xc9, 0xd9, 0x77, 0xc0, 0xd7, 0xcc, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x6c, 0xee,
	0xd7, 0xde, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SimRPCClient is the client API for SimRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimRPCClient interface {
	RecordMetrics(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*Result, error)
}

type simRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewSimRPCClient(cc grpc.ClientConnInterface) SimRPCClient {
	return &simRPCClient{cc}
}

func (c *simRPCClient) RecordMetrics(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/simRPC.simRPC/RecordMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimRPCServer is the server API for SimRPC service.
type SimRPCServer interface {
	RecordMetrics(context.Context, *Metrics) (*Result, error)
}

// UnimplementedSimRPCServer can be embedded to have forward compatible implementations.
type UnimplementedSimRPCServer struct {
}

func (*UnimplementedSimRPCServer) RecordMetrics(ctx context.Context, req *Metrics) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordMetrics not implemented")
}

func RegisterSimRPCServer(s *grpc.Server, srv SimRPCServer) {
	s.RegisterService(&_SimRPC_serviceDesc, srv)
}

func _SimRPC_RecordMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimRPCServer).RecordMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simRPC.simRPC/RecordMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimRPCServer).RecordMetrics(ctx, req.(*Metrics))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simRPC.simRPC",
	HandlerType: (*SimRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordMetrics",
			Handler:    _SimRPC_RecordMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k8s_sim.proto",
}
