# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k8s_sim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='k8s_sim.proto',
  package='simRPC',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rk8s_sim.proto\x12\x06simRPC\"\x7f\n\x07Metrics\x12\x1c\n\x05\x63lock\x18\x01 \x01(\x0b\x32\r.simRPC.Clock\x12\x1c\n\x05nodes\x18\x02 \x01(\x0b\x32\r.simRPC.Nodes\x12\x1a\n\x04pods\x18\x03 \x01(\x0b\x32\x0c.simRPC.Pods\x12\x1c\n\x05queue\x18\x04 \x01(\x0b\x32\r.simRPC.Queue\"\x1a\n\x05\x43lock\x12\x11\n\tclock_Key\x18\x01 \x01(\t\"\"\n\x05Nodes\x12\x19\n\x11nodes_metrics_key\x18\x01 \x01(\t\" \n\x04Pods\x12\x18\n\x10pods_metrics_key\x18\x01 \x01(\t\"\"\n\x05Queue\x12\x19\n\x11queue_metrics_key\x18\x01 \x01(\t\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32<\n\x06simRPC\x12\x32\n\rRecordMetrics\x12\x0f.simRPC.Metrics\x1a\x0e.simRPC.Result\"\x00\x62\x06proto3')
)




_METRICS = _descriptor.Descriptor(
  name='Metrics',
  full_name='simRPC.Metrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clock', full_name='simRPC.Metrics.clock', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='simRPC.Metrics.nodes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pods', full_name='simRPC.Metrics.pods', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue', full_name='simRPC.Metrics.queue', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=152,
)


_CLOCK = _descriptor.Descriptor(
  name='Clock',
  full_name='simRPC.Clock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clock_Key', full_name='simRPC.Clock.clock_Key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=180,
)


_NODES = _descriptor.Descriptor(
  name='Nodes',
  full_name='simRPC.Nodes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes_metrics_key', full_name='simRPC.Nodes.nodes_metrics_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=216,
)


_PODS = _descriptor.Descriptor(
  name='Pods',
  full_name='simRPC.Pods',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pods_metrics_key', full_name='simRPC.Pods.pods_metrics_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=250,
)


_QUEUE = _descriptor.Descriptor(
  name='Queue',
  full_name='simRPC.Queue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_metrics_key', full_name='simRPC.Queue.queue_metrics_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=286,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='simRPC.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='simRPC.Result.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=312,
)

_METRICS.fields_by_name['clock'].message_type = _CLOCK
_METRICS.fields_by_name['nodes'].message_type = _NODES
_METRICS.fields_by_name['pods'].message_type = _PODS
_METRICS.fields_by_name['queue'].message_type = _QUEUE
DESCRIPTOR.message_types_by_name['Metrics'] = _METRICS
DESCRIPTOR.message_types_by_name['Clock'] = _CLOCK
DESCRIPTOR.message_types_by_name['Nodes'] = _NODES
DESCRIPTOR.message_types_by_name['Pods'] = _PODS
DESCRIPTOR.message_types_by_name['Queue'] = _QUEUE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metrics = _reflection.GeneratedProtocolMessageType('Metrics', (_message.Message,), {
  'DESCRIPTOR' : _METRICS,
  '__module__' : 'k8s_sim_pb2'
  # @@protoc_insertion_point(class_scope:simRPC.Metrics)
  })
_sym_db.RegisterMessage(Metrics)

Clock = _reflection.GeneratedProtocolMessageType('Clock', (_message.Message,), {
  'DESCRIPTOR' : _CLOCK,
  '__module__' : 'k8s_sim_pb2'
  # @@protoc_insertion_point(class_scope:simRPC.Clock)
  })
_sym_db.RegisterMessage(Clock)

Nodes = _reflection.GeneratedProtocolMessageType('Nodes', (_message.Message,), {
  'DESCRIPTOR' : _NODES,
  '__module__' : 'k8s_sim_pb2'
  # @@protoc_insertion_point(class_scope:simRPC.Nodes)
  })
_sym_db.RegisterMessage(Nodes)

Pods = _reflection.GeneratedProtocolMessageType('Pods', (_message.Message,), {
  'DESCRIPTOR' : _PODS,
  '__module__' : 'k8s_sim_pb2'
  # @@protoc_insertion_point(class_scope:simRPC.Pods)
  })
_sym_db.RegisterMessage(Pods)

Queue = _reflection.GeneratedProtocolMessageType('Queue', (_message.Message,), {
  'DESCRIPTOR' : _QUEUE,
  '__module__' : 'k8s_sim_pb2'
  # @@protoc_insertion_point(class_scope:simRPC.Queue)
  })
_sym_db.RegisterMessage(Queue)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'k8s_sim_pb2'
  # @@protoc_insertion_point(class_scope:simRPC.Result)
  })
_sym_db.RegisterMessage(Result)



_SIMRPC = _descriptor.ServiceDescriptor(
  name='simRPC',
  full_name='simRPC.simRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=314,
  serialized_end=374,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecordMetrics',
    full_name='simRPC.simRPC.RecordMetrics',
    index=0,
    containing_service=None,
    input_type=_METRICS,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMRPC)

DESCRIPTOR.services_by_name['simRPC'] = _SIMRPC

# @@protoc_insertion_point(module_scope)
